-- MySQL Script generated by MySQL Workbench
-- Mon May  8 10:44:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agente` (
  `idAgente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `habilidade` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAgente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vilao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vilao` (
  `idvilao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `num_crimes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvilao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missao` (
  `idmissao` INT NOT NULL,
  `data` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NULL,
  `duracao` INT NULL,
  `vilao_idvilao` INT NOT NULL,
  PRIMARY KEY (`idmissao`),
  INDEX `fk_missao_vilao_idx` (`vilao_idvilao` ASC) VISIBLE,
  CONSTRAINT `fk_missao_vilao`
    FOREIGN KEY (`vilao_idvilao`)
    REFERENCES `mydb`.`vilao` (`idvilao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agente_has_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agente_has_missao` (
  `Agente_idAgente` INT NOT NULL,
  `missao_idmissao` INT NOT NULL,
  PRIMARY KEY (`Agente_idAgente`, `missao_idmissao`),
  INDEX `fk_Agente_has_missao_missao1_idx` (`missao_idmissao` ASC) VISIBLE,
  INDEX `fk_Agente_has_missao_Agente1_idx` (`Agente_idAgente` ASC) VISIBLE,
  CONSTRAINT `fk_Agente_has_missao_Agente1`
    FOREIGN KEY (`Agente_idAgente`)
    REFERENCES `mydb`.`Agente` (`idAgente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agente_has_missao_missao1`
    FOREIGN KEY (`missao_idmissao`)
    REFERENCES `mydb`.`missao` (`idmissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
