-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 10:32:28 2023
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sakila` ;
USE `sakila` ;

-- -----------------------------------------------------
-- Table `sakila`.`Artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Artigo` (
  `idArtigo` INT NOT NULL,
  `tiulo` VARCHAR(45) NOT NULL,
  `dataApresentacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Instituicao` (
  `idInstituicao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Autor` (
  `idAutor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `Artigo_idArtigo` INT NOT NULL,
  `Instituicao_idInstituicao` INT NOT NULL,
  PRIMARY KEY (`idAutor`, `Artigo_idArtigo`, `Instituicao_idInstituicao`),
  CONSTRAINT `fk_Autor_Artigo`
    FOREIGN KEY (`Artigo_idArtigo`)
    REFERENCES `sakila`.`Artigo` (`idArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_Instituicao1`
    FOREIGN KEY (`Instituicao_idInstituicao`)
    REFERENCES `sakila`.`Instituicao` (`idInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Participantes` (
  `idParticipantes` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParticipantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`TransacaoBancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`TransacaoBancaria` (
  `idTransacaoBancaria` INT NOT NULL,
  `dataTransacao` VARCHAR(45) NOT NULL,
  `Participantes_idParticipantes` INT NOT NULL,
  PRIMARY KEY (`idTransacaoBancaria`, `Participantes_idParticipantes`),
  CONSTRAINT `fk_TransacaoBancaria_Participantes1`
    FOREIGN KEY (`Participantes_idParticipantes`)
    REFERENCES `sakila`.`Participantes` (`idParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sakila`.`Participantes_has_Artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila`.`Participantes_has_Artigo` (
  `Participantes_idParticipantes` INT NOT NULL,
  `Artigo_idArtigo` INT NOT NULL,
  PRIMARY KEY (`Participantes_idParticipantes`, `Artigo_idArtigo`),
  CONSTRAINT `fk_Participantes_has_Artigo_Participantes1`
    FOREIGN KEY (`Participantes_idParticipantes`)
    REFERENCES `sakila`.`Participantes` (`idParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participantes_has_Artigo_Artigo1`
    FOREIGN KEY (`Artigo_idArtigo`)
    REFERENCES `sakila`.`Artigo` (`idArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
