DROP DATABASE C207;

CREATE DATABASE IF NOT EXISTS C207;

USE C207;

CREATE TABLE IF NOT EXISTS alunos(
	matricula INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    curso VARCHAR(45),
    nome VARCHAR(45)
);

CREATE USER IF NOT EXISTS 'Monitor' IDENTIFIED BY '1234';

ALTER TABLE alunos MODIFY curso INT NOT NULL;
ALTER TABLE alunos ADD endereco VARCHAR(45);
ALTER TABLE alunos DROP nome;

DROP DATABASE IF EXISTS C207;
DROP TABLE alunos;
DROP USER 'Monitor';

SHOW DATABASES;
SHOW GRANTS FOR 'Monitor';
SHOW TABLES;